// src/components/CartDrawer.tsx
<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted, computed } from 'vue'
import CartItemComponent from './CartItem.vue'
import EmptyStateComponent from './EmptyState.vue'
import { useCartStore } from '../stores/cartStore'

const props = defineProps<{
  isOpen: boolean
  onClose: () => void
}>()

const emit = defineEmits<{
  close: []
}>()

const cartStore = useCartStore()
const drawerRef = ref<HTMLDivElement | null>(null)
const isAnimating = ref(false)

const items = computed(() => cartStore.items)
const total = computed(() => cartStore.total)
const itemCount = computed(() => cartStore.itemCount)
const animationState = computed(() => cartStore.animationState)
const lastAddedItemId = computed(() => cartStore.lastAddedItemId)

let animationTimer: ReturnType<typeof setTimeout> | null = null

watch(animationState, (newState) => {
  if (newState === 'spinning') {
    isAnimating.value = true
    animationTimer = setTimeout(() => {
      isAnimating.value = false
      animationTimer = null
    }, 1000)
  }
})

onUnmounted(() => {
  if (animationTimer) {
    clearTimeout(animationTimer)
  }
})

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Escape' && props.isOpen) {
    emit('close')
  }
}

onMounted(() => {
  document.addEventListener('keydown', handleKeyDown)
})

onUnmounted(() => {
  document.removeEventListener('keydown', handleKeyDown)
  document.body.style.overflow = ''
})

watch(() => props.isOpen, (newIsOpen) => {
  if (newIsOpen) {
    document.body.style.overflow = 'hidden'
  } else {
    document.body.style.overflow = ''
  }
})

const handleOverlayClick = (event: MouseEvent) => {
  if (event.target === event.currentTarget) {
    emit('close')
  }
}

const handleRemoveItem = (itemId: string) => {
  cartStore.removeItem(itemId)
}

const handleUpdateQuantity = (itemId: string, quantity: number) => {
  cartStore.updateQuantity(itemId, quantity)
}

const handleCheckout = () => {
  emit('close')
}
</script>

<template>
  <Teleport to="body">
    <div
      v-if="props.isOpen"
      class="fixed inset-0 z-50 flex justify-end"
      data-testid="cart-drawer-overlay"
    >
      <div
        class="absolute inset-0 bg-black/50 transition-opacity duration-300"
        @click="handleOverlayClick"
      />
      <div
        ref="drawerRef"
        class="relative w-full max-w-md bg-crimson-950 border-l border-crimson-800/50 shadow-2xl transform transition-transform duration-300 ease-in-out"
        :class="props.isOpen ? 'translate-x-0' : 'translate-x-full'"
        role="dialog"
        aria-modal="true"
        aria-label="Shopping cart"
        data-testid="cart-drawer"
      >
        <div class="flex flex-col h-full">
          <div class="flex items-center justify-between px-6 py-4 border-b border-crimson-800/50">
            <h2 class="text-xl font-bold text-crimson-100">
              Cart
              <span
                v-if="itemCount > 0"
                class="ml-2 text-sm font-normal text-crimson-400"
                data-testid="cart-item-count"
              >
                ({{ itemCount }} {{ itemCount === 1 ? 'item' : 'items' }})
              </span>
            </h2>
            <button
              class="text-crimson-400 hover:text-crimson-200 transition-colors p-1"
              @click="emit('close')"
              aria-label="Close cart"
              data-testid="cart-close-button"
            >
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          <div class="flex-1 overflow-y-auto px-6 py-4">
            <div v-if="items.length === 0" data-testid="cart-empty-state">
              <EmptyStateComponent
                title="Your cart is empty"
                message="Add some items to get started"
                icon="cart"
                action="Browse Events"
              />
            </div>
            <div v-else class="space-y-2" data-testid="cart-items-list">
              <CartItemComponent
                v-for="item in items"
                :key="item.id"
                :item="item"
                :is-animating="isAnimating && item.id === lastAddedItemId"
                @remove="handleRemoveItem"
                @update-quantity="handleUpdateQuantity"
              />
            </div>
          </div>

          <div
            v-if="items.length > 0"
            class="border-t border-crimson-800/50 px-6 py-4 space-y-4"
            data-testid="cart-footer"
          >
            <div class="flex justify-between items-center text-lg">
              <span class="text-crimson-300">Total</span>
              <span class="font-bold text-crimson-100" data-testid="cart-total">
                ${{ total.toFixed(2) }}
              </span>
            </div>
            <button
              class="w-full bg-crimson-600 hover:bg-crimson-500 text-white font-semibold py-3 px-6 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              :disabled="items.length === 0"
              @click="handleCheckout"
              data-testid="cart-checkout-button"
            >
              Proceed to Checkout
            </button>
          </div>
        </div>
      </div>
    </div>
  </Teleport>
</template>

// components/CartDrawer.tsx
import React, { useEffect, useRef } from 'react';
import { useCart } from '../hooks/useCart';
import VinylSpinner from './VinylSpinner';
import GothicEmptyState from './GothicEmptyState';
import ThemedButton from './ThemedButton';

interface CartDrawerProps {
  isOpen: boolean;
  onClose: () => void;
}

const CartDrawer: React.FC<CartDrawerProps> = ({ isOpen, onClose }) => {
  const {
    items,
    total,
    itemCount,
    animationState,
    lastAddedItemId,
    removeItem,
    updateQuantity,
    clearCart,
  } = useCart();

  const drawerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && isOpen) {
        onClose();
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isOpen]);

  const handleOverlayClick = (event: React.MouseEvent<HTMLDivElement>) => {
    if (event.target === event.currentTarget) {
      onClose();
    }
  };

  const formatPrice = (price: number): string => {
    return `$${price.toFixed(2)}`;
  };

  const renderCartItems = () => {
    if (items.length === 0) {
      return (
        <GothicEmptyState
          title="Empty Record Shelves"
          message="Your collection awaits... add some vinyl to begin your journey through the darkness."
        />
      );
    }

    return (
      <div className="cart-items" data-testid="cart-items">
        {items.map((item) => (
          <div
            key={item.id}
            className={`cart-item ${lastAddedItemId === item.id && animationState === 'spinning' ? 'cart-item--spinning' : ''}`}
            data-testid={`cart-item-${item.id}`}
          >
            <div className="cart-item__image">
              <img src={item.imageUrl} alt={item.title} />
            </div>
            <div className="cart-item__details">
              <h3 className="cart-item__title">{item.title}</h3>
              <p className="cart-item__price">{formatPrice(item.price)}</p>
              <div className="cart-item__quantity">
                <button
                  onClick={() => updateQuantity(item.id, item.quantity - 1)}
                  className="cart-item__quantity-btn"
                  aria-label={`Decrease quantity of ${item.title}`}
                >
                  -
                </button>
                <span className="cart-item__quantity-value">{item.quantity}</span>
                <button
                  onClick={() => updateQuantity(item.id, item.quantity + 1)}
                  className="cart-item__quantity-btn"
                  aria-label={`Increase quantity of ${item.title}`}
                >
                  +
                </button>
              </div>
            </div>
            <button
              onClick={() => removeItem(item.id)}
              className="cart-item__remove"
              aria-label={`Remove ${item.title} from cart`}
            >
              &times;
            </button>
          </div>
        ))}
      </div>
    );
  };

  return (
    <>
      {isOpen && (
        <div
          className="cart-overlay"
          data-testid="cart-overlay"
          onClick={handleOverlayClick}
        />
      )}
      <div
        ref={drawerRef}
        className={`cart-drawer ${isOpen ? 'cart-drawer--open' : ''}`}
        data-testid="cart-drawer"
        role="dialog"
        aria-modal="true"
        aria-label="Shopping cart"
      >
        <div className="cart-drawer__header">
          <h2 className="cart-drawer__title">
            Your Collection
            {itemCount > 0 && (
              <span className="cart-drawer__count" data-testid="cart-count">
                ({itemCount})
              </span>
            )}
          </h2>
          <button
            onClick={onClose}
            className="cart-drawer__close"
            aria-label="Close cart"
          >
            &times;
          </button>
        </div>

        {animationState === 'spinning' && (
          <div className="cart-drawer__spinner-overlay" data-testid="vinyl-spinner-overlay">
            <VinylSpinner />
          </div>
        )}

        <div className="cart-drawer__content">
          {renderCartItems()}
        </div>

        {items.length > 0 && (
          <div className="cart-drawer__footer">
            <div className="cart-drawer__total">
              <span>Total:</span>
              <span className="cart-drawer__total-value" data-testid="cart-total">
                {formatPrice(total)}
              </span>
            </div>
            <div className="cart-drawer__actions">
              <ThemedButton
                onClick={clearCart}
                variant="secondary"
                data-testid="clear-cart-button"
              >
                Clear Collection
              </ThemedButton>
              <ThemedButton
                onClick={() => {
                  // Navigate to checkout - will be implemented in T001-4
                  onClose();
                }}
                variant="primary"
                data-testid="checkout-button"
              >
                Proceed to Ritual
              </ThemedButton>
            </div>
          </div>
        )}
      </div>

      <style jsx>{`
        .cart-overlay {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(0, 0, 0, 0.7);
          z-index: 1000;
          animation: fadeIn 0.3s ease;
        }

        .cart-drawer {
          position: fixed;
          top: 0;
          right: 0;
          bottom: 0;
          width: 400px;
          max-width: 100vw;
          background: #1a1a1a;
          border-left: 2px solid #8B0000;
          z-index: 1001;
          transform: translateX(100%);
          transition: transform 0.3s ease;
          display: flex;
          flex-direction: column;
          box-shadow: -4px 0 20px rgba(0, 0, 0, 0.5);
        }

        .cart-drawer--open {
          transform: translateX(0);
        }

        .cart-drawer__header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 1.5rem;
          border-bottom: 1px solid #333;
          background: linear-gradient(180deg, #2a0a0a 0%, #1a1a1a 100%);
        }

        .cart-drawer__title {
          font-family: 'Cinzel', serif;
          font-size: 1.5rem;
          color: #8B0000;
          margin: 0;
        }

        .cart-drawer__count {
          font-size: 1rem;
          color: #666;
          margin-left: 0.5rem;
        }

        .cart-drawer__close {
          background: none;
          border: none;
          color: #666;
          font-size: 2rem;
          cursor: pointer;
          padding: 0.5rem;
          line-height: 1;
          transition: color 0.2s;
        }

        .cart-drawer__close:hover {
          color: #8B0000;
        }

        .cart-drawer__spinner-overlay {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(0, 0, 0, 0.8);
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 10;
          animation: fadeIn 0.2s ease;
        }

        .cart-drawer__content {
          flex: 1;
          overflow-y: auto;
          padding: 1rem;
        }

        .cart-items {
          display: flex;
          flex-direction: column;
          gap: 1rem;
        }

        .cart-item {
          display: flex;
          gap: 1rem;
          padding: 1rem;
          background: #222;
          border: 1px solid #333;
          border-radius: 4px;
          transition: border-color 0.2s;
          position: relative;
        }

        .cart-item:hover {
          border-color: #8B0000;
        }

        .cart-item--spinning {
          animation: vinylSpin 1.5s ease;
        }

        .cart-item__image {
          width: 80px;
          height: 80px;
          flex-shrink: 0;
          border-radius: 50%;
          overflow: hidden;
          border: 2px solid #333;
        }

        .cart-item__image img {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .cart-item__details {
          flex: 1;
          min-width: 0;
        }

        .cart-item__title {
          font-family: 'Cinzel', serif;
          font-size: 1rem;
          color: #fff;
          margin: 0 0 0.5rem;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }

        .cart-item__price {
          font-size: 0.9rem;
          color: #8B0000;
          margin: 0 0 0.5rem;
        }

        .cart-item__quantity {
          display: flex;
          align-items: center;
          gap: 0.5rem;
        }

        .cart-item__quantity-btn {
          background: #333;
          border: 1px solid #555;
          color: #fff;
          width: 28px;
          height: 28px;
          border-radius: 4px;
          cursor: pointer;
          font-size: 1rem;
          display: flex;
          align-items: center;
          justify-content: center;
          transition: all 0.2s;
        }

        .cart-item__quantity-btn:hover {
          background: #8B0000;
          border-color: #8B0000;
        }

        .cart-item__quantity-value {
          font-size: 1rem;
          color: #fff;
          min-width: 24px;
          text-align: center;
        }

        .cart-item__remove {
          background: none;
          border: none;
          color: #666;
          font-size: 1.5rem;
          cursor: pointer;
          padding: 0.25rem;
          line-height: 1;
          transition: color 0.2s;
          position: absolute;
          top: 0.5rem;
          right: 0.5rem;
        }

        .cart-item__remove:hover {
          color: #8B0000;
        }

        .cart-drawer__footer {
          padding: 1.5rem;
          border-top: 1px solid #333;
          background: #1a1a1a;
        }

        .cart-drawer__total {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 1rem;
          font-family: 'Cinzel', serif;
          font-size: 1.2rem;
          color: #fff;
        }

        .cart-drawer__total-value {
          color: #8B0000;
          font-size: 1.4rem;
        }

        .cart-drawer__actions {
          display: flex;
          gap: 1rem;
        }

        .cart-drawer__actions > :global(*) {
          flex: 1;
        }

        @keyframes fadeIn {
          from {
            opacity: 0;
          }
          to {
            opacity: 1;
          }
        }

        @keyframes vinylSpin {
          from {
            transform: rotate(0deg);
          }
          to {
            transform: rotate(360deg);
          }
        }

        @media (max-width: 480px) {
          .cart-drawer {
            width: 100vw;
          }
        }
      `}</style>
    </>
  );
};

export default CartDrawer;
